name: Despliege en Railway
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI moderna
        run: npm install -g railway

      - name: Desplegar a Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --project 43fa6b8c-d103-4cb3-b366-b805914b11f3 --service deportes-frontend
