name: Deploy a Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Verificar que railway.json exista
        run: |
          echo "Contenido de railway.json:"
          cat railway.json

      - name: Desplegar a Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up

